### ISSUE TITLE
Crash on map load with Twilight Forest 2.3.4, compatibility issue

### ISSUE THREAD

**Issue by cocopuffs99** [SteveKunG/More-Planets-GC#5]
Crash with Twilight Forest installed, but error goes away when removing More Planets 1.2.1.  Using Galacticraft build #297  Not sure but here is the crash log:

http://pastebin.com/LKHUaL38

Also notified Twilight Forest mod author: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276258-the-twilight-forest-v2-3-4-snow-queen-troll?comment=10270

#10270, 10271, and 10272

**Comment by cocopuffs99** [comment]
Thanks Steve! Your mod is amazing btw =)

**Comment by SteveKunG** [comment]
Hi. It's not my mod conflict with Twilight Forest mod. I already test it, I think that bug with other mod.

**Comment by cocopuffs99** [comment]
Hi Steve! Did you test it with twilight forest installed?  When I remove your mod I no longer get the crash. Thanks

**Comment by SteveKunG** [comment]
Here is my testing. No problem : http://youtu.be/ak0LtkYXC3g

**Comment by cocopuffs99** [comment]
Thanks for the testing video! Is that with More Planets also installed?  

I don't mean I can't run Twilight Forest by itself on vanilla minecraft, the issue was that Twilight Forest with Galacticraft + More Planets gets the crash- after removing More Planets I no longer get the crash.  Since then, I have started a new modpack so I will try adding More Planets to it and see if I am still getting the crash (to check for file corruption in my files with the old modpack).

**Comment by cocopuffs99** [comment]
RE: Just tried re-installing with new modpack- same crash.

Modpack works with latest Galacticraft (#307)and Twilight Forest; on adding More Planets mod (1.2.3) the game crashes.  Crash log:  http://pastebin.com/QuKjQakp

**Comment by SteveKunG** [comment]
Please using latest of Galacticraft Build version.

**Comment by Cracks777** [comment]
cocopuffs99 do you use teamspeak?

**Comment by cocopuffs99** [comment]
@Cracks777 No but I can get it set up if I need to; I know plenty of my buddies and colleagues use it. =)

@SteveKunG Got it working!!! Everything working fine now in the just recently updated versions of all 3 mods (Twilight Forest 1.7.10-2.3.5, Galacticraft 1.7-3.0.11.309, and More Planets 1.7.10-1.2.4).  Thanks

**Comment by Cracks777** [comment]
@cocopuffs99 if you want to set it up or need help let me know, id love to help, also is there another way to reach you than on here? i hate blowing up these type of post just talking.

**Comment by Cracks777** [comment]
i have a teamspeak server, do you use skype?

**Comment by cocopuffs99** [comment]
Yes

**Comment by Cracks777** [comment]
my skype name is   Crack.Monkey

**Comment by cocopuffs99** [comment]
I sent you a contact request

**Comment by Cracks777** [comment]
never got one?

**Comment by cocopuffs99** [comment]
Hmm. Still didnt get it? Is that the same spelling (Crack.Monkey)?

**Comment by Cracks777** [comment]
nothing, here is my personal teamspeak server address, if you connect to it you will see me there, i may not be at the computer all the time but you can leave me a message.

ts50.gameservers.com:9290 just copy and paste that in the address box and click connect
