### ISSUE TITLE
Crash on Loading Server For 1.2.3 and 1.2.4 but 1.2.2 works

### ISSUE THREAD

**Issue by Dslacky** [SteveKunG/More-Planets-GC#6]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 01/04/15 16:20
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:101)
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:85)
	at stevekung.mods.moreplanets.core.MorePlanetsCore.preInit(MorePlanetsCore.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3745035264 bytes (3571 MB) / 4208984064 bytes (4014 MB) up to 4208984064 bytes (4014 MB)
	JVM Flags: 2 total; -Xmx4024M -Xms4024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.88.1307 Minecraft Forge 10.13.2.1307 164 mods loaded, 164 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.88.1307} [Forge Mod Loader] (forge-1.7.10-10.13.2.1307-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1307} [Minecraft Forge] (forge-1.7.10-10.13.2.1307-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-beta-14} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Core{6.4.3} [BuildCraft] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Transport{6.4.3} [BC Transport] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Silicon{6.4.3} [BC Silicon] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Factory{6.4.3} [BC Factory] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	additionalpipes{3.4} [Additional Pipes] (additionalpipes-4.2.1.jar) Unloaded->Constructed->Pre-initialized
	IC2{2.2.706-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.706-experimental.jar) Unloaded->Constructed->Pre-initialized
	AdvancedMachines{1.1.3} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) Unloaded->Constructed->Pre-initialized
	AncientWarfare{2.4.83-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AncientWarfareAutomation{2.4.83-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AncientWarfareNEIPlugin{2.4.83-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AncientWarfareNpc{2.4.83-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AncientWarfareStructure{2.4.83-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AncientWarfareVehicle{2.4.83-beta-MC1.7.10} [Ancient Warfare Vehicles] (ancientwarfare-2.4.83-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-beta-14} [Applied Energistics 2] (appliedenergistics2-rv2-beta-14.jar) Unloaded->Constructed->Pre-initialized
	asielib{0.3.10} [asielib] (AsieLib-1.7.10-0.3.10.jar) Unloaded->Constructed->Pre-initialized
	ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) Unloaded->Constructed->Pre-initialized
	AutoFood{59.0.0} [AutoFood] (autofood-59.0.0.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded{1.7.10R2.8.0RC8} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC8} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	Automagy{0.22.1} [Automagy] (Automagy-1.7.10-0.22.1.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC7} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC7-62.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0RC7} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC7-141.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.4.2A2} [Big Reactors] (BigReactors-0.4.2A2.jar) Unloaded->Constructed->Pre-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized
	BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed->Pre-initialized
	Botania{r1.6-173} [Botania] (Botania r1.6-173.jar) Unloaded->Constructed->Pre-initialized
	redgear_core{2.2.0} [Red Gear Core] (RedGearCore-1.7.10-2.2.0.jar) Unloaded->Constructed->Pre-initialized
	redgear_brewcraft{1.2.3} [Brewcraft] (Brewcraft-1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Builders{6.4.3} [BC Builders] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	BuildCraft|Energy{6.4.3} [BC Energy] (buildcraft-6.4.3.jar) Unloaded->Constructed->Pre-initialized
	CalendarGui{1.0.1} [Calendar Gui] (CalendarGui-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.1.321} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized
	chisel{2.3.9.36} [Chisel 2] (Chisel2-2.3.9.36.jar) Unloaded->Constructed->Pre-initialized
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized
	cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-5.jar) Unloaded->Constructed->Pre-initialized
	OmnisCore{0.0.5} [Omnis Core] (OmnisCore-0.0.5.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed->Pre-initialized
	dimensionalPockets{0.10.4} [Dimensional Pockets] (dimensionalPockets-0.10.4 (1).jar) Unloaded->Constructed->Pre-initialized
	DraconicEvolution{1.0.0e} [Draconic Evolution] (Draconic-Evolution-1.7.10-v1.0.0e.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.8.366} [Ender IO] (EnderIO-1.7.10-2.2.8.366.jar) Unloaded->Constructed->Pre-initialized
	EnderStorage{1.4.5.29} [EnderStorage] (EnderStorage-1.7.10-1.4.5.29-universal.jar) Unloaded->Constructed->Pre-initialized
	EnderZoo{1.7.10-1.0.10.25} [Ender Zoo] (EnderZoo-1.7.10-1.0.10.25.jar) Unloaded->Constructed->Pre-initialized
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized
	EE3{0.2.450} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.2.450.jar) Unloaded->Constructed->Pre-initialized
	Equivalence{1.1.0} [Equivalence] (Equivalence-1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized
	extracells{2.2.59} [ExtraCells] (ExtraCells-1.7.10-2.2.59b89.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) Unloaded->Constructed->Pre-initialized
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized
	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.308.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.308.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	HardcoreDarkness{1.2} [Hardcore Darkness] (HardcoreDarkness-1.2.jar) Unloaded->Constructed->Pre-initialized
	HardcoreEnderExpansion{1.7.1} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.7.1.jar) Unloaded->Constructed->Pre-initialized
	IC2NuclearControl{2.2.0a-Yolo} [Nuclear Control 2] (IC2NuclearControl-2.2.0a-Yolo.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	LogisticsPipes{0.8.3.108} [Logistics Pipes] (logisticspipes-0.8.3.108.jar) Unloaded->Constructed->Pre-initialized
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized
	magicalcrops{4.0.0_BETA_13a} [Magical Crops] (magicalcrops-4.0.0_BETA_13a.jar) Unloaded->Constructed->Pre-initialized
	MagicBees{1.7.10-2.1.22} [Magic Bees] (magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
	malisiscore{1.7.10-0.11.3} [MalisisCore] (malisiscore-1.7.10-0.11.3 (1).jar) Unloaded->Constructed->Pre-initialized
	malisisdoors{1.7.10-1.5.1} [Malisis' Doors] (malisisdoors-1.7.10-1.5.1.jar) Unloaded->Constructed->Pre-initialized
	MemoryCleaner{1.0} [Memory Cleaner] (MemoryCleaner-1.4-mc.1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized
	minechem{5.0.5.385} [Minechem] (Minechem-1.7.10-5.0.5.385.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC8} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC8} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC8} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC8} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC8} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC8} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC8} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC8} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC8} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	Mystcraft{0.11.2.01} [Mystcraft] (mystcraft-1.7.10-0.11.2.01.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC8} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.5.14.66} [ProjectRed] (ProjectRed-1.7.10-4.5.14.66-Base.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.5.14.66} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.14.66-World.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC8} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC8} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC8} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC8} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC8} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC8} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC8} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC8} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar) Unloaded->Constructed->Pre-initialized
	MorePlanet{1.2.4} [More Planets] (More-Planets-1.7.10-1.2.4.jar) Unloaded->Constructed->Errored
	Morpheus{1.7.10-1.6.4} [Morpheus] (Morpheus-1.7.10-1.6.4.jar) Unloaded->Constructed->Pre-initialized
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized
	planetguyLib{1.5} [planetguyLib] (PlanetguyLib-1.5.jar) Unloaded->Constructed->Pre-initialized
	PowerConverters{1.7.10-3.0.4.47} [Power Converters] (PowerConverters-1.7.10-3.0.4.47.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.5.14.66} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.14.66-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.5.14.66} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.14.66-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.5.14.66} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.14.66-Compat.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.5.14.66} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.14.66-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.5.14.66} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.14.66-Lighting.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.5.14.66} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.14.66-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	YogpstopLib{2.0.3} [Yogpstop Library] (QuarryPlus-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized
	QuarryPlus{2.0.3} [QuarryPlus] (QuarryPlus-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized
	JAKJ_RedstoneInMotion{2.5.2} [Remain In Motion] (RemainInMotion-2.5.3.jar) Unloaded->Constructed->Pre-initialized
	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) Unloaded->Constructed->Pre-initialized
	Schematica{1.7.5.117} [Schematica] (Schematica-1.7.10-1.7.5.117-universal.jar) Unloaded->Constructed->Pre-initialized
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized
	SolarExpansion{1.5a} [Solar Expansion] (SolarExpansion-Basic-1.5a.jar) Unloaded->Constructed->Pre-initialized
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3 (1).jar) Unloaded->Constructed->Pre-initialized
	statues{2.1.4} [Statues] (Statues Mod V.2.1.4.jar) Unloaded->Constructed->Pre-initialized
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized
	WaslieCore{1.0} [WaslieCore] (WaslieCore-1.0.jar) Unloaded->Constructed->Pre-initialized
	ThaumcraftExtras{1.0} [Thaumcraft Extras 2] (ThaumcraftExtras-2-1.0 BETA-1.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded->Constructed->Pre-initialized
	tradeboothmod{1.7.10.2} [tradeboothmod] (tradebooth.1.7.10.2.jar) Unloaded->Constructed->Pre-initialized
	TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-6.jar) Unloaded->Constructed->Pre-initialized
	witchery{0.23.2} [Witchery] (witchery-1.7.10-0.23.2.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.1.321} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.1.321} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenModsLib crash transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	CoFHCore: -[1.7.10]3.0.0RC7-211
	AE2 Version: beta rv2-beta-14 for Forge 10.13.2.1291
	MineFactoryReloaded: -[1.7.10]2.8.0RC8-86
	ThermalFoundation: -[1.7.10]1.0.0RC7-62
	ThermalExpansion: -[1.7.10]4.0.0RC7-141
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by iExoTicK** [comment]
Me too, tested with cauldron 1307, More Planets 1.2.4 and Galacticraft 309. 
Logs : http://pastebin.com/VKd9Xuwy

**Comment by SteveKunG** [comment]
OK! Thanks for testing.
