### ISSUE TITLE
1.8-1.0.0 Planet Core crashes server and client at startup

### ISSUE THREAD

**Issue by kreezxil** [SteveKunG/More-Planets-GC#8]
client crash report: http://paste.ee/p/I2h44
client fml latest log: https://paste.ee/p/YCK03

 "crashes on server startup"
server crash report: http://pastebin.com/MjLnhDhP
server fml latest: http://pastebin.com/cqhPjfWY

**Comment by SteveKunG** [comment]
Some mods is adding Kiwi? I don't know please send and let's me know that mod name. Thank you.
And please delete Steve's Core 1.8-1.0.0.

**Comment by SteveKunG** [comment]
OK! I already test it, this version I'm not recommended to playing in server. But work find in a client. I'll try to find a way to fix it. Thank you.

**Comment by SteveKunG** [comment]
Good news. I can fix it. Release a new download on tomorrow!

**Comment by kreezxil** [comment]
Cool. :)

**Comment by SteveKunG** [comment]
OK. I'm release it. Please check it out and testing.

**Comment by kreezxil** [comment]
give me link to it, the mcf thread has the old link still

**Comment by SteveKunG** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-2-6-galacticraft-add-on-the
